homepage/urls.py
from django.urls import path
from . import views

app_name = 'homepage'

urlpatterns = [
    path('', views.index, name='index'),
]

story1/urls.py
from django.urls import path
from . import views

app_name = 'story1'

urlpatterns = [
    path('', views.story1home, name='story1home'),
]

story2/urls.py
from django.urls import path
from . import views

app_name = 'story2'

urlpatterns = [
    path('', views.story2home, name='story2home'),
]

story3/urls.py
from django.urls import path
from . import views

app_name = 'story3'

urlpatterns = [
    path('', views.story3home, name='story3home'),
    path('bonus/', views.story3bonus, name='story3bonus'),
]

story5/urls.py
from django.urls import path
from . import views

app_name = 'story5'

urlpatterns = [
    path('', views.story5home, name='story5home'),
    path('form/', views.story5form, name='story5form'),
    path('<int:num>/', views.permatkul, name='permatkul') #path variabel dimasukin lewat sini trs dipake ke view wkwwkwkwk
]

story6/urls.py
from django.urls import path
from . import views

app_name = 'story6'

urlpatterns = [
    path('', views.story6home, name ='story6home'),
    path('form/', views.story6form, name = 'story6form'),
]

story7/urls.py
from django.urls import path
from . import views

app_name = 'story7'

urlpatterns = [
    path('', views.story7home, name='story7home'),
]

story8/urls.py
from django.urls import path
from . import views

app_name = 'story8'

urlpatterns = [
    path('', views.story8home, name='story8home'),
    path('api', views.search, name="api")
]

webdev_stories/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('homepage.urls')),
    path('story1/', include('story1.urls')),
    path('story2/', include('story2.urls')),
    path('story3/', include('story3.urls')),
    path('story5/', include('story5.urls')),
    path('story6/', include('story6.urls')),
    path('story7/', include('story7.urls')),
    path('story8/', include('story8.urls')),
]

story1/models.py
from django.db import models

# Create your models here.

story2/models.py
from django.db import models

# Create your models here.

story3/models.py
from django.db import models

# Create your models here.

story5/models.py
from django.db import models

class sebuah_matkul(models.Model):
    sks_choices = [(1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6)]
    semester_choices = [
        ("Gasal 2019/2020", "Gasal 2019/2020"),
        ("Genap 2019/2020", "Genap 2019/2020"),
        ("Gasal 2020/2021", "Gasal 2020/2021"),
        ("Genap 2020/2021", "Genap 2020/2021"),
        ("Gasal 2021/2022", "Gasal 2021/2022"),
        ("Genap 2021/2022", "Genap 2021/2022"),
    ]
        
    mata_kuliah = models.CharField(max_length = 50)
    dosen_pengajar = models.CharField(max_length = 25)
    jumlah_sks = models.IntegerField(choices=sks_choices, default=1)
    deskripsi = models.TextField(max_length = 200)
    semester_thn = models.CharField(choices=semester_choices, max_length = 20)
    ruang_kelas = models.CharField(max_length = 25)

    def __str__(self): # muncul di admin
        return self.mata_kuliah

story6/models.py
from django.db import models

class Kegiatan(models.Model):
    nama_kegiatan = models.CharField(max_length = 30)

    def __str__(self):
        return self.nama_kegiatan

class Pendaftar(models.Model):
    nama_pendaftar = models.CharField(max_length = 30)
    ikut_kegiatan = models.ForeignKey(Kegiatan, on_delete=models.CASCADE)

    def __str__(self):
        return self.nama_pendaftar

story7/models.py
from django.db import models

# Create your models here.

story8/models.py
from django.db import models

# Create your models here.

story5/forms.py
from django import forms
from .models import sebuah_matkul

class form_matkul(forms.ModelForm):
    class Meta:
        model = sebuah_matkul # nama model
        fields = '__all__' # buat munculin field yg ada di model
        widgets = {
            'mata_kuliah': forms.TextInput(attrs={'class': 'fieldclass'}),
        }

story6/forms.py
from django import forms
from .models import Kegiatan, Pendaftar

class FormKegiatan(forms.ModelForm):
    class Meta:
        model = Kegiatan
        fields = '__all__'

class FormPendaftar(forms.ModelForm):
    class Meta:
        model = Pendaftar
        fields = ['nama_pendaftar']

story1/views.py
from django.shortcuts import render

def story1home(request):
    return render(request, 'story1home.html')

story2/views.py
from django.shortcuts import render

def story2home(request):
    return render(request, 'story2home.html')

story3/views.py
from django.shortcuts import render

def story3home(request):
    return render(request, 'story3home.html')

def story3bonus(request):
    return render(request, 'story3bonus.html')

story5/views.py
from django.shortcuts import render, redirect
from .models import sebuah_matkul
from .forms import form_matkul

def story5home(request):
    items = sebuah_matkul.objects.all()
    context = {'matkul' : items}
    return render(request, 'story5home.html', context)

def story5form(request):
    if request.method == 'POST':
        form = form_matkul(request.POST)
        if form.is_valid():
            form.save()
        return redirect('story5:story5home')
    else:
        form = form_matkul()
        return render(request, 'story5form.html', {'form_matkul':form})

def permatkul(request, num):
    items = sebuah_matkul.objects.get(id=num)
    if request.method == 'POST':
        items.delete()
        return redirect('story5:story5home')
    context = {'matkul': items}
    return render(request, 'story5matkul.html', context)

story6/views.py
from django.shortcuts import render, redirect
from .models import Kegiatan, Pendaftar
from .forms import FormKegiatan, FormPendaftar

def story6home(request):
    items = Kegiatan.objects.all()
    pendaftar = Pendaftar.objects.all()
    context = {'satu_kegiatan' : items}
    form = FormPendaftar()
    if request.method == 'POST':
        kegiatan = Kegiatan.objects.get(id = request.POST['id'])
        peserta = Pendaftar.objects.create(nama_pendaftar=request.POST['nama_pendaftar'], ikut_kegiatan=kegiatan)
        return redirect("story6:story6home")
    context = {"kegiatan" : items, "form_peserta" : form, "peserta": pendaftar}
    return render(request, 'story6home.html', context)

def story6form(request):
    if request.method == 'POST':
        form = FormKegiatan(request.POST)
        if form.is_valid():
            form.save()
        return redirect('story6:story6home')
    else:
        form = FormKegiatan()
        return render(request, 'story6form.html', {'FormKegiatan':form})

story7/views.py
from django.shortcuts import render, redirect

def story7home(request):
    return render(request, 'story7home.html')

story8/views.py
from django.shortcuts import render
from django.http import JsonResponse, response
import urllib3
from json import loads

def story8home(request):
    context = {'page_title': 'API'}
    return render(request, 'story8home.html', context)

def search(request):
    http = urllib3.PoolManager()
    response = http.request(
        'GET', "https://www.googleapis.com/books/v1/volumes?" + request.GET.urlencode())
    context = loads(response.data.decode('utf-8'))
    return JsonResponse(context)

story2/templates/story2home.html
<!DOCTYPE html>
{% load static %}

<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <script src="https://code.jquery.com/jquery-1.10.2.js"></script>
    <link rel="stylesheet" href="{% static 'story2.css' %}">
    <title>Anski Stories</title>
</head>

<body>
    <div class="centered-box">
        <p class="main-header">Anski's Story 2</p>
        <iframe style="border: 1px solid rgba(0, 0, 0, 0.1);"
            width="800" height="450"
            src="https://www.figma.com/embed?embed_host=share&url=https%3A%2F%2Fwww.figma.com%2Ffile%2FRxkom2HF1iOdFYklOti6G3%2FStory-2-PPW%3Fnode-id%3D6%253A32&chrome=DOCUMENTATION"
            allowfullscreen>
        </iframe>
    </div>
    
    <script>
        function changeRes() {
            if (x.matches) {
                document.getElementsByTagName("iframe")[0].setAttribute("width", "250");
                document.getElementsByTagName("iframe")[0].setAttribute("height", "500");
            } else {
                document.getElementsByTagName("iframe")[0].setAttribute("width", "800");
                document.getElementsByTagName("iframe")[0].setAttribute("height", "450");
            }
        }
        var x = window.matchMedia("(max-width: 768px")
        changeRes()
        x.addListener(changeRes)
    </script>
</body>

</html>

story3/templates/story3bonus.html
<!DOCTYPE html>
{% load static %}

<html lang="en">

<head>
    <meta charset="UTF-8">
    <script src="https://code.jquery.com/jquery-1.10.2.js"></script>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{% static 'story3bonus.css' %}">
    <link rel="icon" href="{% static 'logo.svg' %}">
    <title>Anski</title>
</head>

<body>
    {% include 'story3navbar.html' %}

    <img class="nav-decor" src="{% static 'topleft.svg' %}">

    <div class="hero-section">
        <p class="main-header">Dog Pictures</p>
        <div class="pic-container">
            <img class="dog-pic" src="{% static 'shiba1.jpeg' %}">
            <img class="dog-pic" src="{% static 'shiba2.jpeg' %}">
            <img class="dog-pic" src="{% static 'shiba3.jpeg' %}">
            <img class="dog-pic" src="{% static 'shiba4.jpeg' %}">
            <img class="dog-pic" src="{% static 'shiba5.jpeg' %}">
            <img class="dog-pic" src="{% static 'shiba6.jpeg' %}">
            <img class="dog-pic" src="{% static 'shiba7.jpeg' %}">
            <img class="dog-pic" src="{% static 'shiba8.jpeg' %}">
            <img class="dog-pic" src="{% static 'shiba9.jpeg' %}">
        </div>
    </div>
</body>

story3/templates/story3home.html
<!DOCTYPE html>
{% load static %}

<html lang="en">

<head>
    <meta charset="UTF-8">
    <script src="https://code.jquery.com/jquery-1.10.2.js"></script>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{% static 'story3.css' %}">
    <link rel="shortcut icon" href="{% static 'logo.svg' %}" type="image/gif">
    <title>Anski</title>
</head>

<body>
    {% include 'story3navbar.html' %}

    <img class="nav-decor" src="{% static 'topleft.svg' %}">
    <div class="hero-section">
        <div class="things-container tc-hero">
            <img class="profpic" src="{% static 'profpic.png' %}">
            <div class="row-container"> 
                <p class="main-header">Hi! I'm Anski.</p>
                <p class="big-desc">A computer science student compassionate about design and front-end engineering.</p>
            </div>
        </div>
        <img class="hero-line" src="{% static 'hero-line.svg' %}">
    </div>

    <div class="pink-section ps-skills" id="skills">
        <img class="whatido-right-decor" src="{% static 'whatido-dots-right.svg' %}">
        <div class="title-box">
            <img class="line1" src="{% static 'line1.svg' %}">
            <p class="section-header sh-left">what i do</p>
        </div>
        <div class="things-container">
            <div class="for-circles fc-one">
                <p class="subtitle">Learn.</p>
            </div>
            <div class="for-circles fc-two">
                <p class="subtitle">Design.</p>
            </div>
            <div class="for-circles fc-three">
                <p class="subtitle">Code.</p>
            </div>
            <div class="for-circles fc-four">
                <p class="subtitle">Draw.</p>
            </div>
        </div>
        <img class="whatido-left-decor" src="{% static 'whatido-dots-left.svg' %}">
    </div>

    <div class="beige-section" id="experience">
        <img class="desc-right-1" src="{% static 'exp-dotsright.svg' %}">
        <img class="desc-left-1" src="{% static 'exp-circleleft.svg' %}">
        <img class="desc-left-2" src="{% static 'exp-dotsleft.svg' %}">
        <img class="desc-right-2" src="{% static 'exp-circleright.svg' %}">
        <div class="title-box-right">
            <img class="line1" src="{% static 'line2.svg' %}">
            <p class="section-header sh-right">my experience</p>
        </div>
        <div class="relative test2">
            <div class="row how-it-works">
				<div class="col-2 full relative">
					<div class="circle"></div>
				</div>
				<div class="col-6">
					<p class="subtitle subtitle-desc">UI/UX Designer</p>
                    <p class="small-text st-bold">COMPFEST 12 • Feb 2020-Present</p>
                    <ul class="small-text">
                        <li>COMPFEST is one of the biggest IT event run by students, with events such as competition, academy, and talkshows.</li>
                        <li>Participated on designing beautiful webpages on COMPFEST 12's website.</li>
                        <li>Did research and usability testing to understand user's behaviour </li>
                    </ul>
				</div>
			</div>
			
			<!--first section-->
			<div class="row how-it-works">
				<div class="col-2 full relative">
					<div class="circle"></div>
				</div>
				<div class="col-6">
                    <p class="subtitle subtitle-desc">Graphic Designer</p>
                    <p class="small-text st-bold">Fasilkom UI Student Council • Feb 2020-Present</p>
					<ul class="small-text">
                        <li>Designed informative posters for the student council’s social media.</li>
                        <li>Was Project Lead for iMaba, an informative website for Fasilkom's new students.</li>
                        <li>Worked on Boolean, a magazine covering the latest IT news.</li>
                    </ul>
				</div>
			</div>

			<!--third section-->
			<div class="row how-it-works">
				<div class="col-2 top">
					<div class="circle"></div>
				</div>
				<div class="col-6">
					<p class="subtitle subtitle-desc">Teaching Assistant for Intro to Digital Systems</p>
                    <p class="small-text st-bold">Fasilkom Universitas Indonesia • Sep 2020-Present</p>
                    <ul class="small-text">
                        <li>Assist students on digital systems and logical thinking.</li>
                        <li>Grade students’ assignments and projects.</li>
                    </ul>
				</div>
			</div>
        </div>
        
    </div>

    <div class="pink-section ps-contacts" id="contact">
        <div class="title-box">
            <img class="line1" src="{% static 'line1.svg' %}">
            <p class="section-header sh-left">keep in touch</p>
        </div>
        <div class="things-container">
            <a href="https://www.linkedin.com/in/hasiana-emanuela-rajagukguk-1604291a2/" target="_blank" style="text-decoration:none">
                <img class="logos" src="{% static 'LinkedIn.svg' %}" alt="linkedin">
            </a>
            <a href="https://github.com/ansqee" target="_blank" style="text-decoration:none">
                <img class="logos" src="{% static 'Github.svg' %}" alt="github">
            </a>
            <a href="https://gitlab.com/ansqee" target="_blank" style="text-decoration:none">
                <img class="logos" src="{% static 'Gitlab.svg' %}" alt="gitlab">
            </a>
            <a href="https://www.instagram.com/anaemnl/" target="_blank" style="text-decoration:none">
                <img class="logos" src="{% static 'IG.svg' %}" alt="ig">
            </a>
        </div>
    </div>
    
</body>

</html>

story3/templates/story3navbar.html
<!DOCTYPE html>
{% load static %}

<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{% static 'story3nav.css' %}">
    <title>Navbar</title>
</head>

<body>
    <header>
        <a class="logo" href="{% url 'story3:story3home' %}"">
            <img class="icon" src="{% static 'navbat-logo.svg' %}" alt="logo"></a>
        <nav>
            <ul class="nav__links">
                <li><a href="{% url 'story3:story3bonus' %}">Bonus</a></li>
            </ul>
        </nav>
    </header>
</body>
</body>

story7/templates/story7home.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{% static 'story7styles.css' %}">
    <script src="https://code.jquery.com/jquery-3.5.1.js"></script>
    <script src="https://code.jquery.com/ui/1.12.1/jquery-ui.js"></script>
    <script src="{% static 'story7script.js' %}" defer></script>
    <link rel="shortcut icon" href="{% static 'logo.svg' %}" type="image/gif">
    <title>Anski's FAQ</title>
</head>
<body>
    <h1 class="big">FAQ about Anski!</h1>

    <ul id="sortable" class="accordion">

        <li>
            <div class="test" style="display: flex; flex-flow: row nowrap; justify-content: space-between;">
                <a class="toggle parent" href=#>What are you currently doing?</a>
                <div style="display: flex; flex-flow: row nowrap;">
                    <a class="up" href="javascript:void(0);" style="margin-right: 10px;">^</a>
                    <a class="down" href="javascript:void(0);">v</a>
                </div>
            </div>
            <p class="inner">
                I have many activites that fills my days right now, like college, organizations, events, and some side-projects I'm doing on my free time, like drawing illustrations for example.
            </p>
        </li>

        <li>
            <div class="test" style="display: flex; flex-flow: row nowrap; justify-content: space-between;">
                <a class="toggle parent" href=#>What events and organizations are you in right now?</a>
                <div style="display: flex; flex-flow: row nowrap;">
                    <a class="up" href="javascript:void(0);" style="margin-right: 10px;">^</a>
                    <a class="down" href="javascript:void(0);">v</a>
                </div>
            </div>
            <p class="inner">
                For organizations, I'm in BEM right now, on the Media Bureau. You know, designing posters and such. For events, I'm gonna be in the upcoming COMPFEST and Fasilkom Wisuda Ganjil Organizers.
            </p>
        </li>

        <li>
            <div class="test" style="display: flex; flex-flow: row nowrap; justify-content: space-between;">
                <a class="toggle parent" href=#>What achievements have you gotten so far?</a>
                <div style="display: flex; flex-flow: row nowrap;">
                    <a class="up" href="javascript:void(0);" style="margin-right: 10px;">^</a>
                    <a class="down" href="javascript:void(0);">v</a>
                </div>
            </div>
            <p class="inner">
                Other than being able to do 3 (yes, three) assignments in one day without any sleep nor meals, I don't think I've ever achieved anything amazing yet.
            </p>
        </li>

        <li>
            <div class="test" style="display: flex; flex-flow: row nowrap; justify-content: space-between;">
                <a class="toggle parent" href=#>How are you feeling?</a>
                <div style="display: flex; flex-flow: row nowrap;">
                    <a class="up" href="javascript:void(0);" style="margin-right: 10px;">^</a>
                    <a class="down" href="javascript:void(0);">v</a>
                </div>
            </div>
            <p class="inner">
                Kinda bad, thanks for asking! I'm managing though, so it's alright.
            </p>
        </li>

        <li>
            <div class="test" style="display: flex; flex-flow: row nowrap; justify-content: space-between;">
                <a class="toggle parent" href=#>What are the things you like?</a>
                <div style="display: flex; flex-flow: row nowrap;">
                    <a class="up" href="javascript:void(0);" style="margin-right: 10px;">^</a>
                    <a class="down" href="javascript:void(0);">v</a>
                </div>
            </div>
            <p class="inner">
                I like dogs, I like reading manga, I like drawing.. I think that's pretty much it? Oh, I've been into reading novels too lately, even though I'm a slow reader so I don't do it often.
            </p>
        </li>

        <li>
            <div class="test" style="display: flex; flex-flow: row nowrap; justify-content: space-between;">
                <a class="toggle parent" href=#>How's college doing?</a>
                <div style="display: flex; flex-flow: row nowrap;">
                    <a class="up" href="javascript:void(0);" style="margin-right: 10px;">^</a>
                    <a class="down" href="javascript:void(0);">v</a>
                </div>
            </div>
            <p class="inner">
                Honestly, it's not so good since I'm not into the classes, but I'm doing assignments alright so it's okay. I also join (too much) events and organizations that I'm pretty much occupied almost all of the time, but hey, it's enjoyable, sooo..
            </p>
        </li>

        <li>
            <div class="test" style="display: flex; flex-flow: row nowrap; justify-content: space-between;">
                <a class="toggle parent" href=#>Wanna hang out sometime?</a>
                <div style="display: flex; flex-flow: row nowrap;">
                    <a class="up" href="javascript:void(0);" style="margin-right: 10px;">^</a>
                    <a class="down" href="javascript:void(0);">v</a>
                </div>
            </div>
            <p class="inner">
                Sure thing! Actually, if (almost) anyone asks me to talk or just idly chat, I'm into that. Just hmu anytime.
            </p>
        </li>

    </ul>
    
</body>
</html>

story8/templates/story8home.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{% static 'story8styles.css' %}">
    <script src="https://code.jquery.com/jquery-3.5.1.js"></script>
    <script src="{% static 'story8script.js' %}" defer></script>
    <title>Book Search</title>
</head>

<body>

    <h1 style="text-align: center;" class="big">Search Google Books</h1>

    <div>
        <form style="display: flex; flex-flow: row wrap; align-items: center; justify-content: center;" id="search-form">
            <input type="text" id="search-url"/>
            <input class="btn" type="submit" value="Search"/>
        </form>

        <div id="books"></div>
    </div>

</body>

</html>