homepage/urls.py
from django.urls import path
from . import views

app_name = 'homepage'

urlpatterns = [
    path('', views.index, name='index'),
]

story1/urls.py
from django.urls import path
from . import views

app_name = 'story1'

urlpatterns = [
    path('', views.story1home, name='story1home'),
]

story2/urls.py
from django.urls import path
from . import views

app_name = 'story2'

urlpatterns = [
    path('', views.story2home, name='story2home'),
]

story3/urls.py
from django.urls import path
from . import views

app_name = 'story3'

urlpatterns = [
    path('', views.story3home, name='story3home'),
    path('bonus/', views.story3bonus, name='story3bonus'),
]

story5/urls.py
from django.urls import path
from . import views

app_name = 'story5'

urlpatterns = [
    path('', views.story5home, name='story5home'),
    path('form/', views.story5form, name='story5form'),
    path('<int:num>/', views.permatkul, name='permatkul') #path variabel dimasukin lewat sini trs dipake ke view wkwwkwkwk
]

story6/urls.py
from django.urls import path
from . import views

app_name = 'story6'

urlpatterns = [
    path('', views.story6home, name ='story6home'),
    path('form/', views.story6form, name = 'story6form'),
]

story7/urls.py
from django.urls import path
from . import views

app_name = 'story7'

urlpatterns = [
    path('', views.story7home, name='story7home'),
]

story8/urls.py
from django.urls import path
from . import views

app_name = 'story8'

urlpatterns = [
    path('', views.story8home, name='story8home'),
    path('api', views.search, name="api")
]

webdev_stories/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('homepage.urls')),
    path('story1/', include('story1.urls')),
    path('story2/', include('story2.urls')),
    path('story3/', include('story3.urls')),
    path('story5/', include('story5.urls')),
    path('story6/', include('story6.urls')),
    path('story7/', include('story7.urls')),
    path('story8/', include('story8.urls')),
]

story1/models.py
from django.db import models

# Create your models here.

story2/models.py
from django.db import models

# Create your models here.

story3/models.py
from django.db import models

# Create your models here.

story5/models.py
from django.db import models

class sebuah_matkul(models.Model):
    sks_choices = [(1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6)]
    semester_choices = [
        ("Gasal 2019/2020", "Gasal 2019/2020"),
        ("Genap 2019/2020", "Genap 2019/2020"),
        ("Gasal 2020/2021", "Gasal 2020/2021"),
        ("Genap 2020/2021", "Genap 2020/2021"),
        ("Gasal 2021/2022", "Gasal 2021/2022"),
        ("Genap 2021/2022", "Genap 2021/2022"),
    ]
        
    mata_kuliah = models.CharField(max_length = 50)
    dosen_pengajar = models.CharField(max_length = 25)
    jumlah_sks = models.IntegerField(choices=sks_choices, default=1)
    deskripsi = models.TextField(max_length = 200)
    semester_thn = models.CharField(choices=semester_choices, max_length = 20)
    ruang_kelas = models.CharField(max_length = 25)

    def __str__(self): # muncul di admin
        return self.mata_kuliah

story6/models.py
from django.db import models

class Kegiatan(models.Model):
    nama_kegiatan = models.CharField(max_length = 30)

    def __str__(self):
        return self.nama_kegiatan

class Pendaftar(models.Model):
    nama_pendaftar = models.CharField(max_length = 30)
    ikut_kegiatan = models.ForeignKey(Kegiatan, on_delete=models.CASCADE)

    def __str__(self):
        return self.nama_pendaftar

story7/models.py
from django.db import models

# Create your models here.

story8/models.py
from django.db import models

# Create your models here.

story5/forms.py
from django import forms
from .models import sebuah_matkul

class form_matkul(forms.ModelForm):
    class Meta:
        model = sebuah_matkul # nama model
        fields = '__all__' # buat munculin field yg ada di model
        widgets = {
            'mata_kuliah': forms.TextInput(attrs={'class': 'fieldclass'}),
        }

story6/forms.py
from django import forms
from .models import Kegiatan, Pendaftar

class FormKegiatan(forms.ModelForm):
    class Meta:
        model = Kegiatan
        fields = '__all__'

class FormPendaftar(forms.ModelForm):
    class Meta:
        model = Pendaftar
        fields = ['nama_pendaftar']

homepage/views.py
from django.shortcuts import render

def index(request):
    return render(request, 'index.html')

story1/views.py
from django.shortcuts import render

def story1home(request):
    return render(request, 'story1home.html')

story2/views.py
from django.shortcuts import render

def story2home(request):
    return render(request, 'story2home.html')

story3/views.py
from django.shortcuts import render

def story3home(request):
    return render(request, 'story3home.html')

def story3bonus(request):
    return render(request, 'story3bonus.html')

story5/views.py
from django.shortcuts import render, redirect
from .models import sebuah_matkul
from .forms import form_matkul

def story5home(request):
    items = sebuah_matkul.objects.all()
    context = {'matkul' : items}
    return render(request, 'story5home.html', context)

def story5form(request):
    if request.method == 'POST':
        form = form_matkul(request.POST)
        if form.is_valid():
            form.save()
        return redirect('story5:story5home')
    else:
        form = form_matkul()
        return render(request, 'story5form.html', {'form_matkul':form})

def permatkul(request, num):
    items = sebuah_matkul.objects.get(id=num)
    if request.method == 'POST':
        items.delete()
        return redirect('story5:story5home')
    context = {'matkul': items}
    return render(request, 'story5matkul.html', context)

story6/views.py
from django.shortcuts import render, redirect
from .models import Kegiatan, Pendaftar
from .forms import FormKegiatan, FormPendaftar

def story6home(request):
    items = Kegiatan.objects.all()
    pendaftar = Pendaftar.objects.all()
    context = {'satu_kegiatan' : items}
    form = FormPendaftar()
    if request.method == 'POST':
        kegiatan = Kegiatan.objects.get(id = request.POST['id'])
        peserta = Pendaftar.objects.create(nama_pendaftar=request.POST['nama_pendaftar'], ikut_kegiatan=kegiatan)
        return redirect("story6:story6home")
    context = {"kegiatan" : items, "form_peserta" : form, "peserta": pendaftar}
    return render(request, 'story6home.html', context)

def story6form(request):
    if request.method == 'POST':
        form = FormKegiatan(request.POST)
        if form.is_valid():
            form.save()
        return redirect('story6:story6home')
    else:
        form = FormKegiatan()
        return render(request, 'story6form.html', {'FormKegiatan':form})

story7/views.py
from django.shortcuts import render, redirect

def story7home(request):
    return render(request, 'story7home.html')

story8/views.py
from django.shortcuts import render
from django.http import JsonResponse, response
import urllib3
from json import loads

def story8home(request):
    context = {'page_title': 'API'}
    return render(request, 'story8home.html', context)

def search(request):
    http = urllib3.PoolManager()
    response = http.request(
        'GET', "https://www.googleapis.com/books/v1/volumes?" + request.GET.urlencode())
    context = loads(response.data.decode('utf-8'))
    return JsonResponse(context)

story5/templates/story5base.html
<!DOCTYPE html>

{% load static %}

<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=`, initial-scale=1.0">
    <link rel="stylesheet" href="{% static 'story5styles.css' %}">
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js" integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy" crossorigin="anonymous"></script>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    <title>Anski's Course</title>
</head>
<body>
    
    <header>
        <a class="logo" href="#"><img class="icon" src="{% static 'navbar-logo.svg' %}" alt="logo"></a>
        <nav>
            <ul class="nav__links">
                <li><a href="{% url 'story5:story5home' %}">Home</a></li>
                <li><a href="{% url 'story5:story5form' %}">Add course</a></li>
            </ul>
        </nav>
        <p class="menu cta">
            <i class="fa fa-bars"></i>
        </p>
    </header>

    <div id="mobile__menu" class="overlay">
        <a class="close">&times;</a>
        <div class="overlay__content">
            <a class="closetext" href="{% url 'story5:story5home' %}">Home</a>
            <a class="closetext5" href="{% url 'story5:story5form' %}">Add course</a>
        </div>
    </div>
    <script type="text/javascript" src="{% static 'mobile.js' %}"></script>

    {% block content %}
    {% endblock content %}

</body>
</html>

story5/templates/story5form.html
{% extends "story5base.html" %}

{% block content %}


<div class="main-container">
    <h2>Add new course</h2>
    <form method="POST">
        {% csrf_token %}
        <div>
            {{ form_matkul }} <!--buat security-->
        </div>
        
        <button type="submit"><p class="white-text">Submit course</p></button>
    </form>
</div>


{% endblock content %}

story5/templates/story5home.html
{% extends "story5base.html" %}

{% block content %}
{% load static %}

<div class="main-container">
    <h1>Anski's Courses</h1>
    <div class="totalmatkul-container">
        {% for kelas in matkul %}
        <div class="matkul-container">
            <a href='{{ kelas.id }}'>
                <p>{{ kelas.mata_kuliah }}</p>
                <p>{{ kelas.semester_thn }}</p>
            </a>
        </div>
    {% endfor %}
    </div>
    
    <a href='{% url "story5:story5form" %}'>
        <button><p class="white-text">Add course</p></button>
    </a>
</div>


{% endblock content %}

story5/templates/story5matkul.html
{% extends "story5base.html" %}

{% block content %}


<div class="main-container">
    <p>Nama matkul: {{ matkul.mata_kuliah }}</p>
    <p>Nama dosen: {{ matkul.dosen_pengajar }}</p>
    <p>Jumlah SKS: {{ matkul.jumlah_sks }}</p>
    <p>Deksripsi: {{ matkul.deskripsi }}</p>
    <p>Semester: {{ matkul.semester_thn }}</p>
    <p>Ruang Kelas: {{ matkul.ruang_kelas }}</p>
    <form method='POST'>
        {% csrf_token %}
        <button class="red" type="submit"><p class="white-text">Delete course</p></button>
    </form>
</div>


{% endblock content %}

story6/templates/story6form.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <h1>Tambah Kegiatan</h1>
    <form method="POST">
        {% csrf_token %}
        <div>
            {{ FormKegiatan }}
        </div>
        <button type="submit"><p>Submit</p></button>
    </form>
</body>
</html>

story6/templates/story6home.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <h1>List Kegiatan Anski</h1>

    <button >
        <a href="{% url 'story6:story6form' %}">
            Tambah Kegiatan
        </a>
    </button>

    {% for giat in kegiatan %}
        <h3>{{ giat.nama_kegiatan }}</h3>
            {% for orang in peserta %}
                {% if orang.ikut_kegiatan == giat %}
                    <p>{{ orang.nama_pendaftar }}</p>
                {% endif %}
            {% endfor %}

            <form method="POST">
                {% csrf_token %}
                {{ form_peserta }}
                <input type='text' name='id' value='{{ giat.id }}' style='display:none'>
                <button type="submit" id="submit">Tambah Peserta</button>
            </form>
        <br>
    {% endfor %}
</body>
</html>